const axios = require('axios');
const fs = require('fs');
const path = require('path');

const GOTIFY_BASE_URL = process.env.GOTIFY_URL ? process.env.GOTIFY_URL.replace('/message', '') : 'http://gotify:80';
const ADMIN_USER = 'admin';
const ADMIN_PASS = process.env.GOTIFY_ADMIN_PASS || 'admin';
const APP_NAME = 'StealthChat';
const TOKEN_FILE = path.join('/app/data', 'gotify_token.json');

/**
 * 等待 Gotify 服务启动
 */
async function waitForGotify(retries = 30, delay = 2000) {
    console.log(`[Gotify Setup] 正在连接 Gotify: ${GOTIFY_BASE_URL}...`);
    for (let i = 0; i < retries; i++) {
        try {
            await axios.get(`${GOTIFY_BASE_URL}/version`);
            console.log('[Gotify Setup] Gotify 已就绪');
            return true;
        } catch (error) {
            console.log(`[Gotify Setup] 等待 Gotify 启动 (${i + 1}/${retries})...`);
            await new Promise(resolve => setTimeout(resolve, delay));
        }
    }
    throw new Error('Gotify 服务启动超时');
}

/**
 * 自动配置 Gotify Token
 */
async function setupGotify() {
    // 0. 手动环境变量覆盖
    if (process.env.GOTIFY_TOKEN && process.env.GOTIFY_TOKEN !== 'Ahc7pv3uyv4rtv9') {
        console.log('[Gotify Setup] 检测到手动配置的 Token，跳过自动配置');
        return;
    }

    // 1. 尝试从本地持久化文件读取
    if (fs.existsSync(TOKEN_FILE)) {
        try {
            const data = JSON.parse(fs.readFileSync(TOKEN_FILE, 'utf8'));
            if (data.token) {
                process.env.GOTIFY_TOKEN = data.token;
                console.log(`[Gotify Setup] 已从本地文件加载 Token: ${data.token.substring(0, 5)}...`);
                return;
            }
        } catch (e) {
            console.warn('[Gotify Setup] 读取本地 Token 文件失败，将重新生成');
        }
    }

    try {
        await waitForGotify();

        const authHeader = {
            Authorization: 'Basic ' + Buffer.from(`${ADMIN_USER}:${ADMIN_PASS}`).toString('base64')
        };

        // 2. 获取现有应用列表
        const appsRes = await axios.get(`${GOTIFY_BASE_URL}/application`, { headers: authHeader });
        const apps = appsRes.data;
        
        const targetApp = apps.find(app => app.name === APP_NAME);

        // 3. 如果存在旧应用，先删除（因为无法找回 Token）
        if (targetApp) {
            console.log(`[Gotify Setup] 发现现有应用 (ID: ${targetApp.id})，正在重建以获取新 Token...`);
            await axios.delete(`${GOTIFY_BASE_URL}/application/${targetApp.id}`, { headers: authHeader });
        }

        // 4. 创建新应用
        console.log(`[Gotify Setup] 创建新应用: ${APP_NAME}`);
        const createRes = await axios.post(`${GOTIFY_BASE_URL}/application`, {
            name: APP_NAME,
            description: 'Auto-generated by Stealth Chat Server'
        }, { headers: authHeader });
        
        const newToken = createRes.data.token;

        // 5. 保存 Token 到本地文件
        try {
            // 确保目录存在
            const dir = path.dirname(TOKEN_FILE);
            if (!fs.existsSync(dir)){
                fs.mkdirSync(dir, { recursive: true });
            }
            fs.writeFileSync(TOKEN_FILE, JSON.stringify({ token: newToken, updatedAt: new Date() }, null, 2));
            console.log(`[Gotify Setup] Token 已保存到: ${TOKEN_FILE}`);
        } catch (e) {
            console.error('[Gotify Setup] 警告: 无法保存 Token 到文件:', e.message);
        }

        // 6. 设置环境变量
        process.env.GOTIFY_TOKEN = newToken;
        console.log(`[Gotify Setup] Token 自动配置成功: ${newToken.substring(0, 5)}...`);

    } catch (error) {
        console.error('[Gotify Setup] 自动配置失败:', error.message);
        if (error.response) {
            console.error('[Gotify Setup] 响应详情:', error.response.status, error.response.data);
        }
    }
}

module.exports = { setupGotify };
